apiVersion : v1
kind : Secret
metadata:
  name : mysql-secrets
data:
  username : petclinic
  password : petclinic

apiVersion : v1
kind : ConfigMap
metadata:
  name : db-config
data:
  host : mysql
  dbName: petclinic